apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 891593725051.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 891593725051.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 04094f1f
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
