apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- name: 371159325218.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newName: 371159325218.dkr.ecr.ap-northeast-2.amazonaws.com/demo-frontend
  newTag: 27e8c8b5
resources:
- ../../base
patchesStrategicMerge:
- front-deployment-patch.yaml
- front-service-patch.yaml
